MAPRHADOOP-99 Added support for jmxagent at JMX_REMOTEHOST

diff --git a/hadoop-yarn-project/hadoop-yarn/bin/yarn b/hadoop-yarn-project/hadoop-yarn/bin/yarn
--- a/hadoop-yarn-project/hadoop-yarn/bin/yarn
+++ b/hadoop-yarn-project/hadoop-yarn/bin/yarn
@@ -208,6 +208,10 @@ if [ -z "$MAPR_JMXSSL" ]; then
     MAPR_JMXSSL="false"
 fi
 
+if [ -z "$MAPR_JMX_LOGIN_CONFIG" ]; then
+    MAPR_JMX_LOGIN_CONFIG="hadoop_simple"
+fi
+
 if [ -z "$MAPR_JMXDISABLE" ] && [ -z "$MAPR_JMXLOCALHOST" ] && [ -z "$MAPR_JMXREMOTEHOST" ]; then
     logJmxMsg "No MapR JMX options given - defaulting to local binding"
 fi
@@ -215,15 +219,35 @@ fi
 if [ -z "$MAPR_JMXDISABLE" ] || [ "$MAPR_JMXDISABLE" = 'false' ]; then
     # default setting for localBinding
     MAPR_JMX_OPTS="-Dcom.sun.management.jmxremote"
+
+    if [ "$MAPR_JMXLOCALHOST" = "true" ] && [ "$MAPR_JMXREMOTEHOST" = "true" ]; then
+        logJmxMsg "WARNING: Both MAPR_JMXLOCALHOST and MAPR_JMXREMOTEHOST options are enabled - defaulting to MAPR_JMXLOCALHOST config"
+        MAPR_JMXREMOTEHOST=false
+    fi
+
     if [ "$MAPR_JMXAUTH" = "true" ]; then
         if [ "$isSecure" = "true" ]; then
-            if [ -f "$MAPR_HOME/conf/jmxremote.password" ] && [ -f "$MAPR_HOME/conf/jmxremote.access" ]; then
-                MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.authenticate=true \
-                    -Dcom.sun.management.jmxremote.password.file=$MAPR_HOME/conf/jmxremote.password \
-                    -Dcom.sun.management.jmxremote.access.file=$MAPR_HOME/conf/jmxremote.access"
+            if [ "$MAPR_JMXREMOTEHOST" = "true" ]; then
+                if [ -f "${MAPR_HOME:-/opt/mapr}/conf/mapr.login.conf" ] && \
+                   [ -f "${MAPR_HOME:-/opt/mapr}/conf/jmxremote.access" ]; then
+                      MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.authenticate=true \
+                          -Djava.security.auth.login.config=${MAPR_HOME:-/opt/mapr}/conf/mapr.login.conf \
+                          -Dmapr.jmx.agent.login.config=$MAPR_JMX_LOGIN_CONFIG \
+                          -Dcom.sun.management.jmxremote.access.file=${MAPR_HOME:-/opt/mapr}/conf/jmxremote.access"
+                else
+                    logJmxMsg "JMX login config or access file missing - not starting since we are in secure mode"
+                    exit 1
+                fi
             else
-                logJmxMsg "JMX password and/or access files missing - not starting since we are in secure mode"
-                exit 1
+                if [ -f "${MAPR_HOME:-/opt/mapr}/conf/jmxremote.password" ] && \
+                   [ -f "${MAPR_HOME:-/opt/mapr}/conf/jmxremote.access" ]; then
+                       MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.authenticate=true \
+                          -Dcom.sun.management.jmxremote.password.file=${MAPR_HOME:-/opt/mapr}/conf/jmxremote.password \
+                          -Dcom.sun.management.jmxremote.access.file=${MAPR_HOME:-/opt/mapr}/conf/jmxremote.access"
+                else
+                    logJmxMsg "JMX password and/or access files missing - not starting since we are in secure mode"
+                    exit 1
+                fi
             fi
         else
             logJmxMsg "JMX Authentication configured - not starting since we are not in secure mode"
@@ -233,10 +257,6 @@ if [ -z "$MAPR_JMXDISABLE" ] || [ "$MAPR_JMXDISABLE" = 'false' ]; then
         MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.authenticate=false"
     fi
 
-    if [ "$MAPR_JMXLOCALHOST" = "true" ] && [ "$MAPR_JMXREMOTEHOST" = "true" ]; then
-        logJmxMsg "WARNING: Both MAPR_JMXLOCALHOST and MAPR_JMXREMOTEHOST options are enabled - defaulting to MAPR_JMXLOCALHOST config"
-        MAPR_JMXREMOTEHOST=false
-    fi
     if [ "$MAPR_JMXLOCALHOST" = "true" ] || [ "$MAPR_JMXREMOTEHOST" = "true" ]; then
         if [ "$MAPR_JMXSSL" = "true" ]; then
             MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.ssl=true"
@@ -248,6 +268,13 @@ if [ -z "$MAPR_JMXDISABLE" ] || [ "$MAPR_JMXDISABLE" = 'false' ]; then
             MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Djava.rmi.server.hostname=localhost \
                 -Dcom.sun.management.jmxremote.host=localhost \
                 -Dcom.sun.management.jmxremote.local.only=true"
+        else
+            if [ -f "${MAPR_HOME:-/opt/mapr}/lib/jmxagent.jar" ]; then
+                MAPR_JMX_OPTS="-javaagent:${MAPR_HOME:-/opt/mapr}/lib/jmxagent.jar $MAPR_JMX_OPTS"
+            else
+                logJmxMsg "jmxagent.jar file missed"
+                exit 1
+            fi
         fi
 
         case "$COMMAND" in
@@ -296,11 +323,12 @@ if [ -z "$MAPR_JMXDISABLE" ] || [ "$MAPR_JMXDISABLE" = 'false' ]; then
             MAPR_JMX_OPTS=""
         else
             if [ "$MAPR_JMXLOCALHOST" = "true" ]; then
+                MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.port=$MAPR_JMX_PORT"
                 logJmxMsg "Enabling TCP JMX for $COMMAND only on localhost port $MAPR_JMX_PORT"
             else
+                MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dmapr.jmx.agent.port=$MAPR_JMX_PORT"
                 logJmxMsg "Enabling TCP JMX for $COMMAND on port $MAPR_JMX_PORT"
             fi
-            MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.port=$MAPR_JMX_PORT"
         fi
     fi
 
